name: Select target action
description: Configure the matrix job directory in GitHub Label
branding:
  icon: git-pull-request
  color: blue

inputs:
  config_file:
    description: 'config file path'
    required: false
    default: '.deploy_target.json'
  token:
    default: "${{ github.token }}"
    required: false
    description: "GITHUB_TOKEN"

outputs:
  matrix-targets:
    description: "List of targets"
    value: ${{ steps.generate_matrix.outputs.targets }}

runs:
  using: composite
  steps:
    - name: Generate matrix
      id: generate_matrix
      uses: phuonghp-arent/select-target-action/generate-matrix@main
      with:
        config_file: ${{ inputs.config_file }}
